### ISSUE TITLE
info doesn't display anything when using typescript

### ISSUE THREAD

**Issue by jwir3** [LukePammant/pretty-logger#4]
I recently switched our project, @foamfactory/shipout to use typescript. However, when running using the built/packaged typescript files, I noticed that `info` function calls are not appearing.

This is an example from a project that is using the version of `shipout` based on the `main` branch of the repository:

![image](https://user-images.githubusercontent.com/997106/137773608-00dbe311-8af2-4507-a7de-865cf08db007.png)

Similarly, in the tests for `shipout` itself, `info` calls do not appear in the console:

![image](https://user-images.githubusercontent.com/997106/137773801-3bbb1dad-8847-4ae9-8df1-e313ecacf5aa.png)

The code for this log statement is:

```
export function CLIAsync(args, privateKey, isTestMode=false) {
  return new Promise((resolve, reject) => {

    // args is pruned to eliminate node and the name of the called executable,
    // assuming you invoked it with bin/shipout.js
    let workingDir;

    if (args.length > 0) {
        workingDir = args[0];
    } else {
      workingDir = process.cwd();
    }

    // Initialize logger and config store
    let logger = new Logger({
      showTimestamp: false,
      info: "gray",
      error: "red",
      warn: "yellow",
      debug: "green",
      prefix: '[' + `Main Process`.green + ']'
    });

    let configStore = new ConfigStore(path.resolve(workingDir), logger,
                                      isTestMode);

    if (isTestMode) {
      Logger.setLevel('debug');
      // Logger.setLevel('warning', true);
    } else if (configStore.getIsVerboseMode()) {
      Logger.setLevel('debug');
    } else {
      Logger.setLevel('info', true);
    }

    logger.info(`Shipout v${packageJson.version} initialized`);

    let filePacker = new FilePacker(configStore);

...
```

As can be seen, it should be running in `info` mode, and the line in the above graphic should say something like:
```
Shipout v0.1.8 intialized
```

Instead, a blank line is emitted.

**Comment by jwir3** [comment]
One thing to note: Prior to switching to typescript, this library worked quite well, and had no issues that I could ascertain.

**Comment by jwir3** [comment]
LOL. This is super embarrassing, but it was my color theme on my new laptop. :man_facepalming: 

Sorry for the spam.

**Comment by LukePammant** [comment]
Haha no problem! Happens to the best of us :)
